# Generated by Django 4.0.5 on 2022-06-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100)),
                ('profesor', models.TextField(max_length=70)),
                ('categoria', models.TextField(max_length=30)),
                ('capitulos', models.IntegerField(max_length=8)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
