# Generated by Django 4.0.5 on 2022-06-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['fechaCreacion'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='cursos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografia'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='capitulos',
            field=models.IntegerField(verbose_name='Secciones'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='categoria',
            field=models.TextField(max_length=30, verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha en que se creo'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='No. Identificacion'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.TextField(max_length=100, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='profesor',
            field=models.TextField(max_length=70, verbose_name='Maestro del Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecho en que se Actualizo'),
        ),
    ]
