# Generated by Django 4.0.5 on 2022-07-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_options_cursos_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoComentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Alta')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Creador')),
            ],
        ),
    ]
