# Generated by Django 4.0.5 on 2022-07-03 17:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_cursocomentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursocomentario',
            name='comentario',
            field=ckeditor.fields.RichTextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='cursocomentario',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Curso del Comentario'),
        ),
    ]
