# Generated by Django 4.0.5 on 2022-08-04 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_cursocomentario_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioCurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('usuario', models.TextField(verbose_name='Usuario')),
                ('mensaje', models.TextField(verbose_name='Comentario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Comentario Curso',
                'verbose_name_plural': 'Comentarios Cursos',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='cursocomentario',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterField(
            model_name='cursocomentario',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Curso En El Que Desea Comentar'),
        ),
    ]
